version: '3.8'

services:
  streamlit:
    build: .
    container_name: hello-world-app
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.fileWatcherType=poll