services:
  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "33000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pickup_generator
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
